"""
Test _apply_selected_indicators directly
"""
import os
import sys
import django
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

import pandas as pd
import numpy as np
from datetime import datetime
from ai_module.backtest_engine import BacktestEngine
from ai_module.technical_indicators import calculate_all_indicators
import logging

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

def create_sample_data(n_days=365):
    dates = pd.date_range(end=datetime.now(), periods=n_days, freq='D')
    np.random.seed(42)
    base_price = 1.1000
    returns = np.random.randn(n_days) * 0.01
    prices = [base_price]
    for ret in returns:
        prices.append(prices[-1] * (1 + ret))
    prices = prices[1:]
    data = pd.DataFrame({
        'open': prices * (1 + np.random.randn(n_days) * 0.002),
        'high': prices * (1 + abs(np.random.randn(n_days)) * 0.005),
        'low': prices * (1 - abs(np.random.randn(n_days)) * 0.005),
        'close': prices,
        'volume': np.random.randint(1000000, 10000000, n_days)
    }, index=dates)
    return data

data = create_sample_data(365)
data = calculate_all_indicators(data)

logger.info(f"Data shape: {data.shape}")
logger.info(f"RSI column exists: {'rsi' in data.columns}")
if 'rsi' in data.columns:
    logger.info(f"RSI stats: min={data['rsi'].min():.2f}, max={data['rsi'].max():.2f}, mean={data['rsi'].mean():.2f}")
    logger.info(f"RSI < 30 count: {(data['rsi'] < 30).sum()}")
    logger.info(f"RSI > 70 count: {(data['rsi'] > 70).sum()}")
    logger.info(f"RSI crossover < 30: {((data['rsi'] < 30) & (data['rsi'].shift(1) >= 30)).sum()}")
    logger.info(f"RSI crossover > 70: {((data['rsi'] > 70) & (data['rsi'].shift(1) <= 70)).sum()}")

engine = BacktestEngine()

logger.info("=" * 80)
logger.info("Testing _apply_selected_indicators with ['rsi']")
logger.info("=" * 80)

signals, reasons = engine._apply_selected_indicators(data, ['rsi'])

buy_signals = int((signals == 1).sum())
sell_signals = int((signals == -1).sum())
total_signals = buy_signals + sell_signals

logger.info(f"Buy signals: {buy_signals}")
logger.info(f"Sell signals: {sell_signals}")
logger.info(f"Total signals: {total_signals}")
logger.info(f"Reasons count: {len(reasons)}")

if total_signals == 0:
    logger.error("❌ NO SIGNALS GENERATED BY _apply_selected_indicators!")
else:
    logger.info("✅ Signals generated successfully")
