# Generated by Django 5.2.7 on 2025-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingstrategy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
