# Generated by Django 5.2.7 on 2025-10-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tradingstrategy_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apiconfiguration',
            unique_together=set(),
        ),
    ]
