# Generated by Django 5.2.7 on 2025-10-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_apiconfiguration_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingstrategy',
            name='parsed_strategy_data',
            field=models.JSONField(blank=True, help_text='Parsed strategy data from NLP processing', null=True),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed'),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='processing_status',
            field=models.CharField(choices=[('not_processed', 'Not Processed'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='not_processed', max_length=20),
        ),
    ]
