# Generated by Django 5.2.7 on 2025-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tradingstrategy_parsed_strategy_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='provider',
            field=models.CharField(choices=[('twelvedata', 'TwelveData'), ('alphavantage', 'Alpha Vantage'), ('oanda', 'OANDA'), ('metalsapi', 'MetalsAPI'), ('gemini', 'Gemini AI (Google AI Studio)')], max_length=50),
        ),
    ]
