# Generated by Django 5.2.7 on 2025-11-02 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_apiconfiguration_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_ticket', models.BigIntegerField(help_text='MT5 position ticket number', unique=True)),
                ('symbol', models.CharField(default='XAUUSD', max_length=50)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('volume', models.FloatField()),
                ('open_price', models.FloatField()),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(default=0.0)),
                ('swap', models.FloatField(default=0.0)),
                ('commission', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tradingstrategy')),
            ],
            options={
                'verbose_name': 'Live Trade',
                'verbose_name_plural': 'Live Trades',
                'ordering': ['-opened_at'],
            },
        ),
    ]
