# Generated by Django 5.2.7 on 2025-11-02 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_livetrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTradingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='فعال/غیرفعال کردن معامله خودکار')),
                ('symbol', models.CharField(default='XAUUSD', help_text='نماد معاملاتی', max_length=50)),
                ('volume', models.FloatField(default=0.01, help_text='حجم معامله به لات')),
                ('max_open_trades', models.IntegerField(default=3, help_text='حداکثر تعداد معاملات باز همزمان')),
                ('check_interval_minutes', models.IntegerField(default=5, help_text='فاصله زمانی بررسی سیگنال (دقیقه)')),
                ('use_stop_loss', models.BooleanField(default=True, help_text='استفاده از حد ضرر')),
                ('use_take_profit', models.BooleanField(default=True, help_text='استفاده از حد سود')),
                ('stop_loss_pips', models.FloatField(default=50.0, help_text='حد ضرر به پیپ')),
                ('take_profit_pips', models.FloatField(default=100.0, help_text='حد سود به پیپ')),
                ('risk_per_trade_percent', models.FloatField(default=2.0, help_text='ریسک به درصد سرمایه در هر معامله')),
                ('last_check_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_trading_settings', to='core.tradingstrategy')),
            ],
            options={
                'verbose_name': 'Auto Trading Settings',
                'verbose_name_plural': 'Auto Trading Settings',
            },
        ),
    ]
