# Generated by Django 5.2.7 on 2025-11-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_otpcode_userprofile_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='متن سوال')),
                ('question_type', models.CharField(help_text='نوع سوال: text, number, choice, multiple_choice, boolean', max_length=50)),
                ('options', models.JSONField(blank=True, help_text='گزینه\u200cهای انتخابی برای سوالات choice', null=True)),
                ('answer', models.TextField(blank=True, help_text='جواب کاربر', null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار جواب'), ('answered', 'پاسخ داده شده'), ('skipped', 'رد شده')], default='pending', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='ترتیب نمایش سوال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, help_text='اطلاعات اضافی برای سوال (مثلاً بخشی از متن که نیاز به توضیح دارد)', null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.tradingstrategy')),
            ],
            options={
                'verbose_name': 'Strategy Question',
                'verbose_name_plural': 'Strategy Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
