# Generated by Django 5.2.7 on 2025-11-04 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_strategy_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان تیکت', max_length=255)),
                ('description', models.TextField(help_text='توضیحات تیکت')),
                ('category', models.CharField(choices=[('technical', 'مسئله فنی'), ('feature', 'درخواست ویژگی'), ('bug', 'گزارش باگ'), ('question', 'سوال'), ('other', 'سایر')], default='other', help_text='دسته\u200cبندی تیکت', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', help_text='اولویت تیکت', max_length=20)),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('resolved', 'حل شده'), ('closed', 'بسته شده')], default='open', help_text='وضعیت تیکت', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_response', models.TextField(blank=True, help_text='پاسخ ادمین')),
                ('admin_user', models.ForeignKey(blank=True, help_text='ادمین پاسخ دهنده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='کاربر ایجاد کننده تیکت', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='متن پیام')),
                ('is_admin', models.BooleanField(default=False, help_text='آیا پیام از طرف ادمین است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(help_text='تیکت مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.ticket')),
                ('user', models.ForeignKey(help_text='ارسال کننده پیام', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'status'], name='core_ticket_user_id_9a0535_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='core_ticket_status_ecde4b_idx'),
        ),
    ]
