# Generated by Django 5.2.7 on 2025-11-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ticket_ticketmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ml', 'Machine Learning'), ('dl', 'Deep Learning'), ('hybrid', 'Hybrid (ML + DL)'), ('auto', 'Auto')], default='auto', max_length=20)),
                ('optimizer_type', models.CharField(default='ml', help_text='ml or dl', max_length=20)),
                ('objective', models.CharField(choices=[('sharpe_ratio', 'Sharpe Ratio'), ('total_return', 'Total Return'), ('win_rate', 'Win Rate'), ('profit_factor', 'Profit Factor'), ('combined', 'Combined')], default='sharpe_ratio', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('failed', 'خطا')], default='pending', max_length=20)),
                ('original_params', models.JSONField(blank=True, help_text='پارامترهای اولیه استراتژی', null=True)),
                ('optimized_params', models.JSONField(blank=True, help_text='پارامترهای بهینه شده', null=True)),
                ('best_score', models.FloatField(blank=True, help_text='بهترین امتیاز بدست آمده', null=True)),
                ('optimization_history', models.JSONField(blank=True, default=list, help_text='تاریخچه بهینه\u200cسازی')),
                ('original_score', models.FloatField(blank=True, help_text='امتیاز استراتژی اولیه', null=True)),
                ('improvement_percent', models.FloatField(blank=True, help_text='درصد بهبود', null=True)),
                ('optimization_settings', models.JSONField(blank=True, default=dict, help_text='تنظیمات بهینه\u200cسازی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='پیام خطا در صورت شکست')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='core.tradingstrategy')),
            ],
            options={
                'verbose_name': 'Strategy Optimization',
                'verbose_name_plural': 'Strategy Optimizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['strategy', 'status'], name='core_strate_strateg_b18eef_idx'), models.Index(fields=['status', 'created_at'], name='core_strate_status_fe723f_idx')],
            },
        ),
    ]
