# Generated by Django 5.2.7 on 2025-11-04 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_strategyoptimization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('entry_condition', 'شرط ورود'), ('exit_condition', 'شرط خروج'), ('risk_management', 'مدیریت ریسک'), ('indicator', 'اندیکاتور'), ('parameter', 'پارامتر'), ('general', 'عمومی')], max_length=20)),
                ('title', models.CharField(help_text='عنوان پیشنهاد', max_length=255)),
                ('description', models.TextField(help_text='توضیحات پیشنهاد')),
                ('recommendation_data', models.JSONField(default=dict, help_text='داده\u200cهای پیشنهاد (JSON)')),
                ('price', models.DecimalField(decimal_places=2, default=150000, help_text='قیمت به تومان', max_digits=12)),
                ('status', models.CharField(choices=[('generated', 'تولید شده'), ('purchased', 'خریداری شده'), ('applied', 'اعمال شده')], default='generated', max_length=20)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('applied_to_strategy', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_recommendations', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='core.tradingstrategy')),
            ],
            options={
                'verbose_name': 'پیشنهاد AI',
                'verbose_name_plural': 'پیشنهادات AI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='موجودی به تومان', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('charge', 'شارژ'), ('payment', 'پرداخت'), ('refund', 'بازگشت وجه')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ به تومان', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='توضیحات تراکنش')),
                ('zarinpal_authority', models.CharField(blank=True, help_text='Authority از زرین\u200cپال', max_length=255)),
                ('zarinpal_ref_id', models.CharField(blank=True, help_text='Ref ID از زرین\u200cپال', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.airecommendation')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.wallet')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
