# Generated by Django 5.2.7 on 2025-11-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_airecommendation_wallet_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyoptimization',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('failed', 'خطا'), ('cancelled', 'لغو شده')], default='pending', max_length=20),
        ),
    ]
