# Generated by Django 5.2.7 on 2025-11-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_strategyoptimization_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDNSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('duckdns', 'DuckDNS (رایگان)'), ('noip', 'No-IP (رایگان)'), ('dynu', 'Dynu (رایگان)'), ('freedns', 'FreeDNS (رایگان)'), ('custom', 'سرویس سفارشی')], default='duckdns', help_text='سرویس DDNS', max_length=50)),
                ('domain', models.CharField(help_text='دامنه (مثلاً: mydomain.duckdns.org)', max_length=255)),
                ('token', models.CharField(blank=True, help_text='توکن یا رمز عبور DDNS', max_length=255)),
                ('username', models.CharField(blank=True, help_text='نام کاربری (برای No-IP و Dynu)', max_length=255)),
                ('password', models.CharField(blank=True, help_text='رمز عبور (برای No-IP و Dynu)', max_length=255)),
                ('update_url', models.URLField(blank=True, help_text='URL به\u200cروزرسانی (برای سرویس سفارشی)', max_length=500)),
                ('is_enabled', models.BooleanField(default=False, help_text='فعال/غیرفعال کردن DDNS')),
                ('update_interval_minutes', models.IntegerField(default=5, help_text='فاصله زمانی به\u200cروزرسانی (دقیقه)')),
                ('last_update', models.DateTimeField(blank=True, help_text='آخرین به\u200cروزرسانی', null=True)),
                ('last_ip', models.CharField(blank=True, help_text='آخرین IP ثبت شده', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DDNS Configuration',
                'verbose_name_plural': 'DDNS Configurations',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_enabled', True)), fields=('is_enabled',), name='unique_active_ddns')],
            },
        ),
    ]
