# Generated by Django 5.2.7 on 2025-11-05 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('charge', 'شارژ'), ('payment', 'پرداخت'), ('refund', 'بازگشت وجه'), ('subscription_purchase', 'خرید اشتراک')], max_length=25),
        ),
        migrations.CreateModel(
            name='GoldPriceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='وضعیت اشتراک')),
                ('start_date', models.DateTimeField(blank=True, help_text='تاریخ شروع اشتراک', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='تاریخ پایان اشتراک', null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=300000, help_text='قیمت ماهانه به تومان', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_price_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اشتراک قیمت طلا',
                'verbose_name_plural': 'اشتراک\u200cهای قیمت طلا',
            },
        ),
    ]
