# Generated by Django 5.2.7 on 2025-11-05 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_transaction_transaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrade',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='آیا این معامله دمو است؟'),
        ),
        migrations.AlterField(
            model_name='livetrade',
            name='mt5_ticket',
            field=models.BigIntegerField(blank=True, help_text='MT5 position ticket number', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.CreateModel(
            name='DemoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=10000.0, help_text='موجودی اولیه حساب دمو (USD)', max_digits=12)),
                ('equity', models.DecimalField(decimal_places=2, default=10000.0, help_text='ارزش فعلی حساب', max_digits=12)),
                ('margin', models.DecimalField(decimal_places=2, default=0.0, help_text='مارجین استفاده شده', max_digits=12)),
                ('free_margin', models.DecimalField(decimal_places=2, default=10000.0, help_text='مارجین آزاد', max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, help_text='سود/زیان کل', max_digits=12)),
                ('leverage', models.IntegerField(default=100, help_text='اهرم حساب')),
                ('is_active', models.BooleanField(default=True, help_text='آیا حساب فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حساب دمو',
                'verbose_name_plural': 'حساب\u200cهای دمو',
            },
        ),
        migrations.CreateModel(
            name='DemoTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('symbol', models.CharField(default='XAU/USD', max_length=50)),
                ('volume', models.FloatField(help_text='حجم معامله')),
                ('open_price', models.FloatField(help_text='قیمت باز شدن')),
                ('current_price', models.FloatField(blank=True, help_text='قیمت فعلی', null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(default=0.0, help_text='سود/زیان فعلی')),
                ('commission', models.FloatField(default=0.0, help_text='کمیسیون')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('margin_used', models.DecimalField(decimal_places=2, default=0.0, help_text='مارجین استفاده شده', max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.demoaccount')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tradingstrategy')),
            ],
            options={
                'verbose_name': 'معامله دمو',
                'verbose_name_plural': 'معاملات دمو',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='livetrade',
            name='demo_trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_trade', to='core.demotrade'),
        ),
        migrations.AddIndex(
            model_name='demotrade',
            index=models.Index(fields=['account', 'status'], name='core_demotr_account_3501c7_idx'),
        ),
        migrations.AddIndex(
            model_name='demotrade',
            index=models.Index(fields=['status', 'opened_at'], name='core_demotr_status_c80f37_idx'),
        ),
    ]
