# Generated by Django 5.2.7 on 2025-11-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_livetrade_is_demo_alter_livetrade_mt5_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='provider',
            field=models.CharField(choices=[('twelvedata', 'TwelveData'), ('alphavantage', 'Alpha Vantage'), ('oanda', 'OANDA'), ('metalsapi', 'MetalsAPI'), ('financialmodelingprep', 'Financial Modeling Prep'), ('nerkh', 'Nerkh.io (قیمت طلا)'), ('gemini', 'Gemini AI (Google AI Studio)'), ('kavenegar', 'Kavenegar (SMS)'), ('google_oauth', 'Google OAuth (Client ID)'), ('zarinpal', 'Zarinpal (Merchant ID)')], max_length=50),
        ),
    ]
