# Generated by Django 5.2.7 on 2025-11-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_apiconfiguration_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='provider',
            field=models.CharField(choices=[('twelvedata', 'TwelveData'), ('alphavantage', 'Alpha Vantage'), ('oanda', 'OANDA'), ('metalsapi', 'MetalsAPI'), ('financialmodelingprep', 'Financial Modeling Prep'), ('nerkh', 'Nerkh.io (قیمت طلا)'), ('gemini', 'Gemini AI (Google AI Studio)'), ('kavenegar', 'Kavenegar (SMS)'), ('google_oauth', 'Google OAuth (Client ID)'), ('zarinpal', 'Zarinpal (Merchant ID)'), ('recaptcha', 'reCAPTCHA v3 (Site Key & Secret Key)')], max_length=50),
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='نام ارائه\u200cدهنده API', max_length=50)),
                ('endpoint', models.CharField(blank=True, help_text='آدرس endpoint فراخوانی شده', max_length=255)),
                ('request_type', models.CharField(default='GET', help_text='نوع درخواست (GET, POST, etc.)', max_length=10)),
                ('status_code', models.IntegerField(blank=True, help_text='کد وضعیت پاسخ', null=True)),
                ('success', models.BooleanField(default=True, help_text='آیا درخواست موفق بود؟')),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, help_text='هزینه به دلار', max_digits=12)),
                ('cost_toman', models.DecimalField(decimal_places=2, default=0.0, help_text='هزینه به تومان', max_digits=12)),
                ('response_time_ms', models.FloatField(blank=True, help_text='زمان پاسخ به میلی\u200cثانیه', null=True)),
                ('error_message', models.TextField(blank=True, help_text='پیام خطا در صورت وجود')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لاگ استفاده از API',
                'verbose_name_plural': 'لاگ\u200cهای استفاده از API',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'created_at'], name='core_apiusa_provide_272cf3_idx'), models.Index(fields=['created_at'], name='core_apiusa_created_28c6d4_idx'), models.Index(fields=['provider', 'success'], name='core_apiusa_provide_f4b1f9_idx')],
            },
        ),
    ]
