# Generated by Django 5.2.7 on 2025-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_apiconfiguration_provider_apiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='data_sources',
            field=models.JSONField(blank=True, default=dict, help_text='اطلاعات منابع داده استفاده شده در بک\u200cتست (مثلاً: provider, symbol, date_range)'),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='analysis_sources',
            field=models.JSONField(blank=True, default=dict, help_text='اطلاعات منابع تحلیل استفاده شده (مثلاً: ai_model, nlp_parser, analysis_method)'),
        ),
    ]
