# Generated by Django 5.2.7 on 2025-11-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_data_sources_and_analysis_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_symbol',
            field=models.CharField(blank=True, default='XAUUSD', help_text='نماد معاملاتی ترجیحی کاربر', max_length=50, null=True),
        ),
    ]
