# Generated by Django 5.2.7 on 2025-11-06 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_preferred_symbol_to_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='کاربری که از API استفاده کرده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['user', 'provider', 'created_at'], name='core_apiusa_user_id_15b67a_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['user', 'created_at'], name='core_apiusa_user_id_eaaaaa_idx'),
        ),
    ]
