# Generated by Django 5.2.7 on 2025-11-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_job_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingstrategy',
            name='user',
            field=models.ForeignKey(blank=True, help_text='کاربر صاحب استراتژی', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['user', 'uploaded_at'], name='core_tradin_user_id_b39581_idx'),
        ),
    ]
