# Generated by Django 5.2.7 on 2025-11-07 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_tradingstrategy_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyMarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان قابل نمایش در مارکت\u200cپلیس', max_length=255)),
                ('headline', models.CharField(blank=True, help_text='خلاصه کوتاه برای جذب مخاطب', max_length=500)),
                ('description', models.TextField(blank=True, help_text='توضیحات کامل مارکت\u200cپلیس')),
                ('shared_text', models.TextField(blank=True, help_text='نسخه متنی/پارامترهای استراتژی برای مطالعه کاربران')),
                ('price', models.DecimalField(decimal_places=2, help_text='هزینه اجاره به تومان', max_digits=12)),
                ('billing_cycle_days', models.PositiveIntegerField(default=30, help_text='مدت دوره اجاره پس از پرداخت (روز)')),
                ('trial_days', models.PositiveIntegerField(default=9, help_text='طول دوره آزمایشی رایگان (روز)')),
                ('trial_backtest_limit', models.PositiveIntegerField(default=3, help_text='حداکثر تعداد بک\u200cتست مجاز در دوره آزمایشی')),
                ('performance_snapshot', models.JSONField(blank=True, default=dict, help_text='خلاصه نتایج تست\u200cهای مالک (بازده، دراودان و ...)')),
                ('sample_results', models.JSONField(blank=True, default=list, help_text='لیست نتایج نمونه بک\u200cتست\u200cها برای نمایش عمومی')),
                ('supported_symbols', models.JSONField(blank=True, default=list, help_text='نمادها/بازارهای پیشنهادی برای این استراتژی')),
                ('tags', models.JSONField(blank=True, default=list, help_text='برچسب\u200cها برای جست\u200cوجو در مارکت\u200cپلیس')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategy Marketplace Listing',
                'verbose_name_plural': 'Strategy Marketplace Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='origin',
            field=models.CharField(choices=[('direct', 'مستقیم'), ('marketplace_trial', 'مارکت\u200cپلیس - دوره آزمایشی'), ('marketplace_active', 'مارکت\u200cپلیس - اشتراک فعال')], default='direct', max_length=30),
        ),
        migrations.CreateModel(
            name='StrategyListingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'دوره آزمایشی'), ('active', 'فعال'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], default='trial', max_length=20)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_expires_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('total_backtests_run', models.PositiveIntegerField(default=0, help_text='تعداد کل بک\u200cتست\u200cهای اجرا شده')),
                ('last_backtest_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_accesses', to='core.transaction')),
                ('user', models.ForeignKey(help_text='کاربر دریافت\u200cکننده دسترسی', on_delete=django.db.models.deletion.CASCADE, related_name='strategy_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategy Listing Access',
                'verbose_name_plural': 'Strategy Listing Accesses',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='marketplace_access',
            field=models.ForeignKey(blank=True, help_text='اگر job از طریق مارکت\u200cپلیس ایجاد شده باشد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.strategylistingaccess'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['origin', 'created_at'], name='core_job_origin_39148c_idx'),
        ),
        migrations.AddField(
            model_name='strategymarketplacelisting',
            name='owner',
            field=models.ForeignKey(help_text='کاربر منتشرکننده', on_delete=django.db.models.deletion.CASCADE, related_name='strategy_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategymarketplacelisting',
            name='strategy',
            field=models.OneToOneField(help_text='استراتژی اصلی که منتشر می\u200cشود', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_entry', to='core.tradingstrategy'),
        ),
        migrations.AddField(
            model_name='strategylistingaccess',
            name='listing',
            field=models.ForeignKey(help_text='استراتژی مارکت\u200cپلیس', on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='core.strategymarketplacelisting'),
        ),
        migrations.AddIndex(
            model_name='strategymarketplacelisting',
            index=models.Index(fields=['is_published', 'published_at'], name='core_strate_is_publ_cf4c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='strategymarketplacelisting',
            index=models.Index(fields=['owner', 'is_published'], name='core_strate_owner_i_14ab37_idx'),
        ),
        migrations.AddIndex(
            model_name='strategylistingaccess',
            index=models.Index(fields=['user', 'status'], name='core_strate_user_id_2d2d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='strategylistingaccess',
            index=models.Index(fields=['listing', 'status'], name='core_strate_listing_be4f81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategylistingaccess',
            unique_together={('listing', 'user')},
        ),
    ]
