# Generated by Django 5.2.7 on 2025-11-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_strategymarketplacelisting_job_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='live_trading_enabled',
            field=models.BooleanField(default=False, help_text='فعال/غیرفعال کردن نمایش بخش معاملات زنده در وب‌سایت'),
        ),
    ]
