# Generated by Django 5.2.7 on 2025-11-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_strategylistingaccess_last_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategylistingaccess',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مبلغ آخرین پرداخت شده', max_digits=12),
        ),
        migrations.AddField(
            model_name='strategylistingaccess',
            name='owner_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مبلغ سهم صاحب استراتژی', max_digits=12),
        ),
        migrations.AddField(
            model_name='strategylistingaccess',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مبلغ سهم پلتفرم', max_digits=12),
        ),
        migrations.AddField(
            model_name='strategylistingaccess',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='درصد سهم پلتفرم', max_digits=5),
        ),
        migrations.AddField(
            model_name='strategymarketplacelisting',
            name='source_result',
            field=models.ForeignKey(blank=True, help_text='نتیجه بک\u200cتست مورد استفاده برای این لیست', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_listings', to='core.result'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, help_text='نیک\u200cنیم قابل نمایش در مارکت\u200cپلیس', max_length=50, null=True, unique=True),
        ),
    ]
