# Generated by Django 5.1.2 on 2025-11-08 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_strategylistingaccess_last_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('charge', 'شارژ'), ('payment', 'پرداخت'), ('refund', 'بازگشت وجه'), ('subscription_purchase', 'خرید اشتراک'), ('gold_api_request', 'درخواست API طلا')], max_length=25),
        ),
        migrations.CreateModel(
            name='UserGoldAPIAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, help_text='نام ارائه\u200cدهنده API (مثلاً: TwelveData, FinancialModelingPrep)', max_length=100)),
                ('api_key', models.CharField(blank=True, help_text='کلید API اختصاصی کاربر', max_length=255)),
                ('source', models.CharField(choices=[('user', 'ثبت توسط کاربر'), ('admin', 'ثبت توسط ادمین')], default='user', help_text='منبع ثبت اطلاعات', max_length=20)),
                ('assigned_by_admin', models.BooleanField(default=False, help_text='آیا این دسترسی توسط ادمین ثبت شده است؟')),
                ('assigned_at', models.DateTimeField(blank=True, help_text='تاریخ ثبت/تخصیص دسترسی فعال', null=True)),
                ('notes', models.TextField(blank=True, help_text='توضیحات تکمیلی برای کاربر یا ادمین')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن دسترسی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_api_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دسترسی API طلا',
                'verbose_name_plural': 'دسترسی\u200cهای API طلا',
            },
        ),
        migrations.CreateModel(
            name='GoldAPIAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('awaiting_admin', 'در انتظار اقدام ادمین'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending_payment', max_length=20)),
                ('preferred_provider', models.CharField(blank=True, help_text='ارائه\u200cدهنده پیشنهادی از سمت کاربر', max_length=100)),
                ('user_notes', models.TextField(blank=True, help_text='توضیحات کاربر هنگام ثبت درخواست')),
                ('admin_notes', models.TextField(blank=True, help_text='توضیحات ادمین')),
                ('price_amount', models.DecimalField(decimal_places=2, default=0, help_text='مبلغ پرداخت شده برای این درخواست', max_digits=12)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, help_text='تاریخ تایید پرداخت', null=True)),
                ('assigned_provider', models.CharField(blank=True, help_text='ارائه\u200cدهنده اختصاص داده شده توسط ادمین', max_length=100)),
                ('assigned_api_key', models.CharField(blank=True, help_text='کلید API اختصاص داده شده', max_length=255)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='تاریخ ثبت API توسط ادمین', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='ادمینی که API را ثبت کرده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gold_api_requests', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, help_text='تراکنش مربوط به این درخواست', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_api_access_request', to='core.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_api_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست API طلا',
                'verbose_name_plural': 'درخواست\u200cهای API طلا',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending_payment', 'awaiting_admin'])), fields=('user',), name='unique_active_gold_api_request_per_user')],
            },
        ),
    ]
