# Generated by Django 5.1.2 on 2025-11-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_transaction_transaction_type_usergoldapiaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='provider',
            field=models.CharField(choices=[('twelvedata', 'TwelveData'), ('alphavantage', 'Alpha Vantage'), ('oanda', 'OANDA'), ('metalsapi', 'MetalsAPI'), ('financialmodelingprep', 'Financial Modeling Prep'), ('nerkh', 'Nerkh.io (قیمت طلا)'), ('gemini', 'Gemini AI (Google AI Studio)'), ('cohere', 'Cohere AI'), ('openrouter', 'OpenRouter'), ('together_ai', 'Together AI'), ('deepinfra', 'DeepInfra'), ('groq', 'GroqCloud'), ('kavenegar', 'Kavenegar (SMS)'), ('google_oauth', 'Google OAuth (Client ID)'), ('zarinpal', 'Zarinpal (Merchant ID)'), ('recaptcha', 'reCAPTCHA v3 (Site Key & Secret Key)')], max_length=50),
        ),
    ]
