# Generated by Django 5.1.2 on 2025-11-08 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_ddnsconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingstrategy',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='استراتژی اصلی کاربر در داشبورد'),
        ),
        migrations.AddField(
            model_name='usergoldapiaccess',
            name='allow_mt5_access',
            field=models.BooleanField(default=False, help_text='اجازه دریافت قیمت طلا از MetaTrader 5 توسط این کاربر (تعیین شده توسط ادمین)'),
        ),
        migrations.AddConstraint(
            model_name='tradingstrategy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primary_strategy_per_user'),
        ),
    ]
