# Generated by Django 5.1.2 on 2025-11-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_apiconfiguration_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apiconfiguration',
            new_name='core_apicon_provide_788217_idx',
            old_name='core_api_provider_user_idx',
        ),
    ]
