# Generated by Django 5.1.2 on 2025-11-13 18:38

from django.conf import settings
from django.db import migrations, models


def ensure_single_primary_strategy(apps, schema_editor):
    TradingStrategy = apps.get_model('core', 'TradingStrategy')
    primary_strategies = (
        TradingStrategy.objects.filter(is_primary=True)
        .order_by('-uploaded_at', '-id')
    )
    primary_to_keep = primary_strategies.first()
    # استراتژی‌های دیگر را از حالت اصلی خارج می‌کنیم
    for strategy in primary_strategies[1:]:
        strategy.is_primary = False
        strategy.save(update_fields=['is_primary'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_core_api_provider_user_idx_core_apicon_provide_788217_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradingstrategy',
            name='unique_primary_strategy_per_user',
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='provider',
            field=models.CharField(choices=[('twelvedata', 'TwelveData'), ('alphavantage', 'Alpha Vantage'), ('oanda', 'OANDA'), ('metalsapi', 'MetalsAPI'), ('financialmodelingprep', 'Financial Modeling Prep'), ('nerkh', 'Nerkh.io (قیمت طلا)'), ('gemini', 'Gemini AI (Google AI Studio)'), ('openai', 'OpenAI (ChatGPT)'), ('cohere', 'Cohere AI'), ('openrouter', 'OpenRouter'), ('together_ai', 'Together AI'), ('deepinfra', 'DeepInfra'), ('groq', 'GroqCloud'), ('kavenegar', 'Kavenegar (SMS)'), ('google_oauth', 'Google OAuth (Client ID)'), ('zarinpal', 'Zarinpal (Merchant ID)'), ('recaptcha', 'reCAPTCHA v3 (Site Key & Secret Key)')], max_length=50),
        ),
        migrations.RunPython(ensure_single_primary_strategy, noop),
        migrations.AddConstraint(
            model_name='tradingstrategy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('is_primary',), name='unique_primary_strategy'),
        ),
    ]
