# Generated by Django 5.1.2 on 2025-11-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_tradingstrategy_unique_primary_strategy_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='google_auth_enabled',
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='provider',
            field=models.CharField(choices=[('twelvedata', 'TwelveData'), ('alphavantage', 'Alpha Vantage'), ('oanda', 'OANDA'), ('metalsapi', 'MetalsAPI'), ('financialmodelingprep', 'Financial Modeling Prep'), ('nerkh', 'Nerkh.io (قیمت طلا)'), ('gemini', 'Gemini AI (Google AI Studio)'), ('openai', 'OpenAI (ChatGPT)'), ('cohere', 'Cohere AI'), ('openrouter', 'OpenRouter'), ('together_ai', 'Together AI'), ('deepinfra', 'DeepInfra'), ('groq', 'GroqCloud'), ('kavenegar', 'Kavenegar (SMS)'), ('zarinpal', 'Zarinpal (Merchant ID)'), ('recaptcha', 'reCAPTCHA v3 (Site Key & Secret Key)')], max_length=50),
        ),
    ]
