# Generated by Django 5.1.2 on 2025-11-18 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_google_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('strategy_processed', 'پردازش استراتژی'), ('strategy_created', 'ایجاد استراتژی'), ('strategy_deleted', 'حذف استراتژی'), ('backtest_run', 'اجرای بک\u200cتست'), ('trade_opened', 'باز کردن معامله'), ('trade_closed', 'بستن معامله'), ('api_key_added', 'افزودن کلید API'), ('api_key_removed', 'حذف کلید API'), ('wallet_charged', 'شارژ کیف پول'), ('profile_updated', 'به\u200cروزرسانی پروفایل'), ('other', 'سایر')], help_text='نوع فعالیت', max_length=50)),
                ('action_description', models.TextField(help_text='توضیحات فعالیت')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی (مثل تعداد توکن\u200cها، نام استراتژی، و غیره)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='کاربری که این فعالیت را انجام داده است', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ فعالیت کاربر',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت کاربران',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_userac_user_id_ee37d3_idx'), models.Index(fields=['action_type', 'created_at'], name='core_userac_action__3ca351_idx'), models.Index(fields=['created_at'], name='core_userac_created_786ebb_idx')],
            },
        ),
    ]
