# Generated by Django 5.1.2 on 2025-11-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_user_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='use_ai_cache',
            field=models.BooleanField(default=True, help_text='استفاده از کش برای پردازش تبدیل متن انسانی به مدل هوش مصنوعی. اگر غیرفعال شود، همیشه از API استفاده می\u200cشود.'),
        ),
    ]
