# Generated by Django 5.1.2 on 2025-11-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_admin_api_keys_systemwide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='provider',
            field=models.CharField(choices=[('twelvedata', 'TwelveData'), ('alphavantage', 'Alpha Vantage'), ('oanda', 'OANDA'), ('metalsapi', 'MetalsAPI'), ('financialmodelingprep', 'Financial Modeling Prep'), ('nerkh', 'Nerkh.io (قیمت طلا)'), ('gemini', 'Gemini AI (Google AI Studio)'), ('openai', 'OpenAI (ChatGPT)'), ('chatgpt', 'ChatGPT (alias of OpenAI)'), ('gpt', 'GPT (alias of OpenAI)'), ('gpt4', 'GPT-4 (alias of OpenAI)'), ('gpt-4', 'GPT-4 (alias of OpenAI)'), ('cohere', 'Cohere AI'), ('openrouter', 'OpenRouter'), ('together_ai', 'Together AI'), ('deepinfra', 'DeepInfra'), ('groq', 'GroqCloud'), ('kavenegar', 'Kavenegar (SMS)'), ('zarinpal', 'Zarinpal (Merchant ID)'), ('recaptcha', 'reCAPTCHA v3 (Site Key & Secret Key)')], max_length=50),
        ),
    ]
