# Generated by Django 5.1.2 on 2025-11-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_apiconfiguration_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='backtest_cost',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='هزینه هر بک\u200cتست به تومان', max_digits=12),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='registration_bonus',
            field=models.DecimalField(decimal_places=2, default=399.0, help_text='مبلغ هدیه ثبت\u200cنام به تومان', max_digits=12),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='token_cost_per_1000',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='هزینه هر 1000 توکن به تومان', max_digits=12),
        ),
    ]
