# Generated by Django 5.1.2 on 2025-11-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_systemsettings_backtest_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='strategy_processing_cost',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='هزینه پردازش هر استراتژی به تومان', max_digits=12),
        ),
    ]
