# Generated by Django 5.1.2 on 2025-12-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_systemsettings_strategy_processing_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='model_costs',
            field=models.JSONField(blank=True, default=dict, help_text="هزینه هر کلمه برای هر مدل به تومان (JSON: {'model_id': cost})"),
        ),
    ]
