# Generated by Django 5.1.2 on 2025-12-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_profit_factor_to_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiconfiguration',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Configuration', 'verbose_name_plural': 'API Configurations'},
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='provider',
            field=models.CharField(choices=[('twelvedata', 'TwelveData'), ('alphavantage', 'Alpha Vantage'), ('oanda', 'OANDA'), ('metalsapi', 'MetalsAPI'), ('financialmodelingprep', 'Financial Modeling Prep'), ('nerkh', 'Nerkh.io (قیمت طلا)'), ('cohere', 'Cohere AI'), ('openrouter', 'OpenRouter'), ('together_ai', 'Together AI'), ('deepinfra', 'DeepInfra'), ('groq', 'GroqCloud'), ('gapgpt', 'GapGPT'), ('kavenegar', 'Kavenegar (SMS)'), ('zarinpal', 'Zarinpal (Merchant ID)'), ('recaptcha', 'reCAPTCHA v3 (Site Key & Secret Key)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='registration_bonus',
            field=models.DecimalField(decimal_places=2, default=39000.0, help_text='مبلغ هدیه ثبت\u200cنام به تومان', max_digits=12),
        ),
    ]
