# Generated by Django 5.1.2 on 2025-12-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_apiconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='registration_bonus',
            field=models.DecimalField(decimal_places=2, default=45000.0, help_text='مبلغ هدیه ثبت\u200cنام به تومان', max_digits=12),
        ),
    ]
