# Generated by Django 5.1.2 on 2025-12-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_systemsettings_registration_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='profit_margin_multiplier',
            field=models.DecimalField(decimal_places=4, default=1.2, help_text='ضریب سود بر قیمت API GapGPT (مثلاً 1.2 = 20% سود، 1.5 = 50% سود)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='model_costs',
            field=models.JSONField(blank=True, default=dict, help_text="هزینه هر کلمه برای هر مدل به تومان (JSON: {'model_id': cost}) - deprecated"),
        ),
    ]
