# Generated by Django 5.1.2 on 2025-12-10 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_add_profit_margin_multiplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='شناسه یکتا جلسه (از frontend)', max_length=255)),
                ('login_time', models.DateTimeField(db_index=True, help_text='زمان ورود')),
                ('logout_time', models.DateTimeField(blank=True, db_index=True, help_text='زمان خروج (null اگر هنوز فعال است)', null=True)),
                ('total_duration', models.IntegerField(default=0, help_text='مدت زمان کل جلسه به ثانیه')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='آدرس IP کاربر', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent مرورگر')),
                ('device_id', models.CharField(blank=True, db_index=True, help_text='شناسه دستگاه (از Device model)', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='آیا جلسه هنوز فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='کاربری که این جلسه را دارد', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جلسه کاربر',
                'verbose_name_plural': 'جلسات کاربران',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(db_index=True, help_text='مسیر صفحه (مثل /dashboard)', max_length=500)),
                ('page_title', models.CharField(blank=True, help_text='عنوان صفحه', max_length=500)),
                ('visit_time', models.DateTimeField(db_index=True, help_text='زمان بازدید')),
                ('duration', models.IntegerField(default=0, help_text='مدت زمان در صفحه به ثانیه')),
                ('referrer', models.CharField(blank=True, help_text='صفحه قبلی (referrer)', max_length=500)),
                ('exit_time', models.DateTimeField(blank=True, help_text='زمان خروج از صفحه', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='آیا بازدید هنوز فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='کاربر (برای دسترسی سریع)', on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='جلسه مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.usersession')),
            ],
            options={
                'verbose_name': 'بازدید صفحه',
                'verbose_name_plural': 'بازدیدهای صفحات',
                'ordering': ['-visit_time'],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'login_time'], name='core_userse_user_id_633a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='core_userse_user_id_11c81c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['login_time'], name='core_userse_login_t_ede1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active', 'login_time'], name='core_userse_is_acti_948dba_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['user', 'visit_time'], name='core_pagevi_user_id_b23e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['page_path', 'visit_time'], name='core_pagevi_page_pa_c54552_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['session', 'visit_time'], name='core_pagevi_session_bdc89e_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['visit_time'], name='core_pagevi_visit_t_3b3ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['is_active', 'visit_time'], name='core_pagevi_is_acti_7cf34c_idx'),
        ),
    ]
