# Generated by Django 5.1.2 on 2025-12-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_improvement_recommendations_to_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotradingsettings',
            name='max_backtest_drawdown',
            field=models.FloatField(blank=True, default=50.0, help_text='حداکثر دراودان مجاز بک\u200cتست (درصد)', null=True),
        ),
        migrations.AddField(
            model_name='autotradingsettings',
            name='min_backtest_return',
            field=models.FloatField(blank=True, default=0.0, help_text='حداقل بازدهی بک\u200cتست (درصد)', null=True),
        ),
        migrations.AddField(
            model_name='autotradingsettings',
            name='min_backtest_trades',
            field=models.IntegerField(blank=True, default=10, help_text='حداقل تعداد معاملات در بک\u200cتست', null=True),
        ),
        migrations.AddField(
            model_name='autotradingsettings',
            name='min_backtest_win_rate',
            field=models.FloatField(blank=True, default=50.0, help_text='حداقل نرخ برد بک\u200cتست (درصد)', null=True),
        ),
        migrations.AddField(
            model_name='autotradingsettings',
            name='require_backtest_result',
            field=models.BooleanField(default=False, help_text='فقط در صورت وجود نتیجه بک\u200cتست موفق معامله کند'),
        ),
        migrations.AddField(
            model_name='autotradingsettings',
            name='use_latest_backtest_only',
            field=models.BooleanField(default=True, help_text='فقط از آخرین نتیجه بک\u200cتست استفاده کند'),
        ),
    ]
