# Generated by Django 5.1.2 on 2025-12-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_add_backtest_filters_to_auto_trading'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_use_auto_trading',
            field=models.BooleanField(default=False, help_text='اجازه استفاده از ترید خودکار بر اساس بک\u200cتست (فقط توسط ادمین فعال می\u200cشود)'),
        ),
    ]
