# Generated by Django 5.1.2 on 2025-12-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_can_use_auto_trading_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotradingsettings',
            name='timeframe',
            field=models.CharField(default='M15', help_text='تایم\u200cفریم معاملاتی (مطابق با بک\u200cتست)', max_length=20),
        ),
    ]
