# Generated by Django 5.1.2 on 2025-12-18 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_demotrade_deployed_result_demotrade_signal_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autotradingsettings',
            name='user',
            field=models.ForeignKey(blank=True, help_text='کاربر استفاده\u200cکننده از ترید خودکار', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_trading_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autotradingsettings',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='فعال/غیرغیرفعال کردن معامله خودکار'),
        ),
        migrations.AlterField(
            model_name='autotradingsettings',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_trading_settings', to='core.tradingstrategy'),
        ),
        migrations.AlterUniqueTogether(
            name='autotradingsettings',
            unique_together={('user', 'strategy')},
        ),
    ]
