# Generated by Django 5.1.2 on 2025-12-18 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_autotradingsettings_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrade',
            name='user',
            field=models.ForeignKey(blank=True, help_text='کاربر صاحب این معامله', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_trades', to=settings.AUTH_USER_MODEL),
        ),
    ]
