# Generated by Django 5.1.2 on 2025-12-28 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_livetrade_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام API Endpoint', max_length=255)),
                ('description', models.TextField(blank=True, help_text='توضیحات API')),
                ('url', models.URLField(help_text='URL کامل API endpoint', max_length=500)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], default='GET', help_text='متد HTTP', max_length=10)),
                ('category', models.CharField(choices=[('trading', 'Trading APIs'), ('data', 'Data Providers'), ('ai', 'AI Services'), ('payment', 'Payment Gateways'), ('notification', 'Notification Services'), ('other', 'Other')], default='other', help_text='دسته\u200cبندی API', max_length=50)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Headers به صورت JSON (مثال: {"Authorization": "Bearer {token}", "Content-Type": "application/json"})')),
                ('query_parameters', models.JSONField(blank=True, default=dict, help_text='Query Parameters به صورت JSON (مثال: {"symbol": "{symbol}", "apikey": "{apikey}"})')),
                ('request_body_template', models.TextField(blank=True, help_text='قالب Request Body (می\u200cتواند JSON یا متن باشد. از {variable} برای placeholder استفاده کنید)')),
                ('expected_status_code', models.IntegerField(blank=True, help_text='کد وضعیت مورد انتظار', null=True)),
                ('response_format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('text', 'Text'), ('binary', 'Binary')], default='json', help_text='فرمت پاسخ مورد انتظار', max_length=50)),
                ('requires_auth', models.BooleanField(default=False, help_text='آیا نیاز به احراز هویت دارد؟')),
                ('auth_type', models.CharField(blank=True, choices=[('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('apikey', 'API Key'), ('custom', 'Custom')], help_text='نوع احراز هویت', max_length=50)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='تنظیمات احراز هویت (JSON: {"header_name": "Authorization", "token_placeholder": "{token}"})')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این endpoint فعال است؟')),
                ('is_public', models.BooleanField(default=False, help_text='آیا این endpoint برای همه کاربران قابل دسترسی است؟')),
                ('tags', models.JSONField(blank=True, default=list, help_text='تگ\u200cها برای جستجو و فیلتر (JSON array: ["tag1", "tag2"])')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='تعداد استفاده از این endpoint')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='آخرین زمان استفاده', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='کاربری که این endpoint را ایجاد کرده (معمولاً ادمین)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Endpoint',
                'verbose_name_plural': 'API Endpoints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='core_apiend_categor_111441_idx'), models.Index(fields=['http_method', 'is_active'], name='core_apiend_http_me_6eedc2_idx'), models.Index(fields=['is_active', 'is_public'], name='core_apiend_is_acti_23d7c7_idx'), models.Index(fields=['created_at'], name='core_apiend_created_c34e74_idx')],
            },
        ),
    ]
