# Generated by Django 5.1.2 on 2025-12-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_add_apiendpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIEndpoint',
        ),
    ]
